name: firstcallingapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.2
  torch_light: ^1.1.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  responsive_builder: ^0.7.1
  gscankit: ^1.0.2
  image_picker: ^1.2.0
  animate_do: ^4.2.0
  add_to_cart_animation: ^2.0.4
  camera: ^0.11.2
  permission_handler: ^12.0.1
  lottie: ^3.3.1
  firebase_messaging: ^15.2.7
  firebase_core: ^3.13.0
  fluttertoast: ^8.2.1
  notched_card: ^0.1.1
  flutter_svg: ^2.2.0
  share_plus: ^11.0.0
  package_info_plus: ^8.3.0
  intl: ^0.20.2
  shimmer: ^3.0.0
  dart_jsonwebtoken: ^3.3.0
  twilio_voice: ^0.3.2+2
  flutter_ringtone_player: ^4.0.0+4












dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
    android: true
    ios: true
    image_path: "assets/playstore.png" # your main icon image







flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/animation.json
    - assets/bus.json
    - assets/bluedot.json
    - assets/applogo.jpg
    - assets/scan.gif
    - assets/torch.png
    - assets/cart.gif


